---

- name: Create MAKER home dir
  file:
    path: "{{ MAKER_HOME }}"
    state: directory

- name: Install glib2 on Ubuntu
  package:
    name: "libglib2.0-dev"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install glib2 on CentOS
  package:
    name: "glib2"
    state: present
  when: ansible_distribution == "CentOS"

- name: Download Exonerate
  get_url:
    url: "{{ EXONERATE_URL }}"
    dest: "{{ MAKER_HOME }}/exonerate-2.4.0.tar.gz"

- name: Unarchive Exonerate
  unarchive:
    src: "{{ MAKER_HOME }}/exonerate-2.4.0.tar.gz"
    dest: "{{ MAKER_HOME }}"
    remote_src: yes

- name: Configure Exonerate
  command: "./configure"
  args:
    chdir: "{{ MAKER_HOME }}/exonerate-2.4.0"

- name: Build Exonerate
  make:
    chdir: "{{ MAKER_HOME }}/exonerate-2.4.0"

- name: Install Exonerate
  make:
    chdir: "{{ MAKER_HOME }}/exonerate-2.4.0"
    target: install

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ MAKER_HOME }}/exonerate-2.4.0.tar.gz"
    - "{{ MAKER_HOME }}/exonerate-2.4.0"
